export type IColors =
  | 'http-get'
  | 'http-post'
  | 'http-put'
  | 'http-patch'
  | 'http-delete'
  | 'grey'
  | 'grey-light'
  | 'grey-dark'
  | 'primary'
  | 'base-white'
  | 'base-blue'
  | 'base-orange'
  | 'base-purple'
  | 'base-yellow'
  | 'base-green'
  | 'base-red'
