export enum IColors {
  httpGet = 'http-get',
  httpPost = 'http-post',
  httpPut = 'http-put',
  httpPatch = 'http-patch',
  httpDelete = 'http-delete',
  grey = 'grey',
  greyLight = 'grey-light',
  greyDark = 'grey-dark',
  primary = 'primary',
  baseWhite = 'base-white',
  baseBlue = 'base-blue',
  baseOrange = 'base-orange',
  basePurple = 'base-purple',
  baseYellow = 'base-yellow',
  baseGreen = 'base-green',
  baseRed = 'base-red',
}
