name: Build and upload assets to release

on:
  release:
    types: [created] # not triggered by draft releases

jobs:
  publish-tauri:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install app dependencies
        run: npm ci

      - name: Prebuild (ubuntu and macos)
        if: matrix.platform != 'windows-latest'
        run: npm run sidecar:build

      - name: Prebuild (windows only)
        if: matrix.platform == 'windows-latest'
        run: npm run sidecar:build-windows

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ github.event.release.id }}
